import {useMutation,useQueryClient} from '@tanstack/react-query';import {createInvoice,createOrder,getOrder,getPurchases} from '../api/queries';import {haptic,openInvoice,showPopup} from '../services/telegram';
const PENDING_KEY='cloud-bot-pending-payment';const PENDING_TTL_MS=30*60*1000;
type Pending={orderId?:string;licenseId:string;idempotencyKey:string;createdAt:number};
function newKey(){return crypto.randomUUID().replace(/-/g,'')}
function readPending():Pending|null{try{const value=JSON.parse(localStorage.getItem(PENDING_KEY)||'null') as Pending|null;if(value?.licenseId&&value?.idempotencyKey&&Date.now()-value.createdAt<PENDING_TTL_MS)return value;localStorage.removeItem(PENDING_KEY)}catch{/* invalid local value */}return null}
function savePending(value:Pending){try{localStorage.setItem(PENDING_KEY,JSON.stringify(value))}catch{/* unavailable */}}
export function hasPendingPayment(orderId:string){return readPending()?.orderId===orderId}
export function clearPendingPayment(){try{localStorage.removeItem(PENDING_KEY)}catch{/* unavailable */}}
export function useCheckout(){const client=useQueryClient();return useMutation({mutationFn:async(licenseId:string)=>{let attempt=readPending();if(attempt?.orderId){const{order}=await getOrder(attempt.orderId);if(order.status==='fulfilled'){const purchases=await getPurchases();const purchase=purchases.items.find(item=>item.order_id===order.id);clearPendingPayment();return{status:'fulfilled' as const,orderId:order.id,purchase}}if(order.status==='pending'&&attempt.licenseId===licenseId)return{status:'processing' as const,orderId:order.id};clearPendingPayment();attempt=null}if(!attempt||attempt.licenseId!==licenseId)attempt={licenseId,idempotencyKey:newKey(),createdAt:Date.now()};savePending(attempt);const{order}=await createOrder(licenseId,attempt.idempotencyKey);attempt={...attempt,orderId:order.id};savePending(attempt);const{invoiceLink}=await createInvoice(order.id);const status=await openInvoice(invoiceLink);if(status!=='paid'){clearPendingPayment();return{status,orderId:order.id}}for(let poll=0;poll<6;poll++){await new Promise(r=>setTimeout(r,700+poll*500));const purchases=await getPurchases();const purchase=purchases.items.find(item=>item.order_id===order.id);if(purchase){clearPendingPayment();await client.invalidateQueries({queryKey:['purchases']});haptic.success();return{status:'fulfilled' as const,orderId:order.id,purchase}}}return{status:'processing' as const,orderId:order.id}},onError:async(error:Error)=>{haptic.error();await showPopup('Не удалось открыть оплату',error.message)}})}
