import {test,expect,type Page} from '@playwright/test';

async function installTelegramMock(page:Page){
  await page.route('https://telegram.org/js/telegram-web-app.js',route=>route.fulfill({contentType:'application/javascript',body:''}));
  await page.addInitScript(()=>{(window as any).Telegram={WebApp:{ready(){},expand(){},enableClosingConfirmation(){},initData:'development-test-init-data',initDataUnsafe:{user:{id:777,first_name:'Premium',username:'cloud_user'}},colorScheme:'dark',viewportStableHeight:844,BackButton:{show(){},hide(){},onClick(){},offClick(){}},MainButton:{setParams(){},showProgress(){},hideProgress(){},onClick(){},offClick(){},hide(){}},SecondaryButton:{setParams(){},onClick(){},offClick(){},hide(){}},HapticFeedback:{impactOccurred(){},selectionChanged(){},notificationOccurred(){}},CloudStorage:{getItem(_k:string,cb:(error:null,value:string)=>void){cb(null,'')},setItem(_k:string,_v:string,cb:(error:null,stored:boolean)=>void){cb(null,true)}},openInvoice(_url:string,cb:(status:string)=>void){cb('cancelled')}}};});
}

test.beforeEach(async({page})=>{await installTelegramMock(page)});

test('premium dashboard is responsive and has no unexpected runtime errors',async({page})=>{const errors:string[]=[];page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('401 (Unauthorized)'))errors.push(msg.text())});await page.goto('/');await expect(page.getByText('Инструменты, которые')).toBeVisible();await expect(page.getByRole('navigation',{name:'Основная навигация'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();expect(errors).toEqual([]);const unnamed=await page.locator('button').evaluateAll(buttons=>buttons.filter(button=>!(button.getAttribute('aria-label')||button.textContent?.trim())).length);expect(unnamed).toBe(0)});

test('primary navigation and local product pages render',async({page})=>{await page.goto('/');await page.getByRole('link',{name:/Поиск/}).click();await expect(page.getByRole('heading',{name:'Найдите готовое решение'})).toBeVisible();await page.goto('/premium');await expect(page.getByRole('heading',{name:/Больше скорости/})).toBeVisible();await page.getByRole('link',{name:/Профиль/}).click();await expect(page.getByText(/Telegram (verified|подтверждён)/i)).toBeVisible()});

test('development catalog exposes only non-template test products and opens checkout CTA',async({page})=>{await page.goto('/search');await expect(page.getByRole('heading',{name:'Найдите готовое решение'})).toBeVisible();expect(await page.locator('select[aria-label="Тип продукта"] option').allTextContents()).not.toContain('Шаблоны');await expect(page.getByText('Запись и бронирование')).toBeVisible({timeout:10_000});await page.getByRole('button',{name:'Открыть Запись и бронирование'}).click();await expect(page.getByRole('heading',{name:'Запись и бронирование'})).toBeVisible();await expect(page.getByRole('button',{name:'Купить за Stars'})).toBeVisible();});

test('profile is fully formed and settings controls are actionable',async({page})=>{await page.goto('/profile');await expect(page.getByRole('heading',{name:'Premium'})).toBeVisible();await expect(page.getByText('Ваш профиль')).toBeVisible();await expect(page.getByRole('button',{name:'Открыть настройки'})).toBeVisible();await expect(page.getByRole('button',{name:'История покупок'})).toBeVisible();await page.getByRole('button',{name:'Открыть настройки'}).click();await expect(page.getByRole('heading',{name:'Настройки'})).toBeVisible();await expect(page.getByRole('heading',{name:'Интерфейс',exact:true})).toBeVisible();await expect(page.getByText('Приватность и уведомления')).toBeVisible();await expect(page.getByRole('combobox',{name:'Тема интерфейса'})).toBeVisible();await expect(page.getByRole('switch',{name:'Приватный режим'})).toBeVisible();});

test('all secondary routes render without runtime failures',async({page})=>{const routes:[string,string][]=[['/settings','Настройки'],['/notifications','Уведомления'],['/referral','Делитесь инструментами'],['/statistics','Статистика'],['/history','История'],['/achievements','Достижения'],['/leaderboard','Личный рейтинг'],['/payments','Платежи'],['/subscription','Подписка и доступ'],['/support','Мы рядом'],['/faq','Частые вопросы'],['/about','Cloud Bot'],['/terms','Условия использования'],['/privacy','Конфиденциальность'],['/favorites','Избранное']];for(const[route,title]of routes){await test.step(route,async()=>{await page.goto(route);await expect(page.getByRole('heading',{name:title,exact:true}).first()).toBeVisible({timeout:10_000})})}await page.close()});

test('profile settings gear opens the settings screen without console errors',async({page})=>{const errors:string[]=[];page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});page.on('pageerror',err=>errors.push(err.message));await page.goto('/profile');const gear=page.getByRole('button',{name:'Открыть настройки'});await expect(gear).toBeVisible();await gear.click();await expect(page.getByRole('heading',{name:'Настройки'})).toBeVisible();expect(page.url()).toContain('/settings');expect(errors).toEqual([])});

test('project admin route denies guest access without runtime errors',async({page})=>{await page.addInitScript(()=>{if(window.Telegram?.WebApp)window.Telegram.WebApp.initData=''});await page.goto('/admin/projects');await expect(page.getByText(/Нужен вход|Доступ запрещён/)).toBeVisible()});

test('admin full sales flow: product, license plan, publish, catalog, checkout',async({page})=>{const orders:Array<{status:number;body:string}>=[];page.on('response',async r=>{if(r.url().includes('/api/orders')&&r.request().method()==='POST'){const t=await r.text();orders.push({status:r.status(),body:t})}});const slug='e2e-lp-'+Date.now().toString(36);await page.goto('/profile');await page.getByRole('button',{name:/Управление товарами/}).click();await expect(page.getByRole('heading',{name:'Добавить проект'})).toBeVisible();await expect(page.getByLabel('Название')).toBeVisible();await page.waitForTimeout(600);await page.getByLabel('Название').fill('E2E License Product');await page.getByLabel('Slug').fill(slug);await page.getByLabel('Тип').selectOption('module');await page.getByLabel('Категория').fill('Тест');await page.getByLabel('Результат для клиента').fill('Тест');await page.getByRole('button',{name:'Создать draft'}).click();await expect(page.getByText(/Проект создан как draft/)).toBeVisible();await expect(page.getByRole('heading',{name:'Тариф и цена'})).toBeVisible();await page.getByLabel('Название тарифа').fill('Стандарт E2E');await page.getByLabel(/Цена \(⭐ Stars\)/).fill('123');await page.getByRole('button',{name:'Сохранить тариф'}).click();await expect(page.getByText(/Тариф сохранён/)).toBeVisible();await expect(page.getByText('123 ⭐')).toBeVisible();await page.setInputFiles('input[type=file]',{name:'readme.txt',mimeType:'text/plain',buffer:Buffer.from('e2e test product description without secrets')});await page.getByRole('button',{name:'Проверить и загрузить'}).click();await expect(page.getByText(/Файл проверен: approved/)).toBeVisible();await page.getByRole('button',{name:'Опубликовать'}).click();await expect(page.getByText(/опубликован и доступен покупателям/)).toBeVisible();await page.goto('/search');await expect(page.getByRole('button',{name:`Открыть E2E License Product`}).first()).toBeVisible({timeout:10_000});await page.getByRole('button',{name:`Открыть E2E License Product`}).first().click();await expect(page.getByRole('heading',{name:'E2E License Product'}).first()).toBeVisible();await expect(page.getByText('Стандарт E2E')).toBeVisible();await expect(page.getByText('123 ⭐').first()).toBeVisible();await page.getByRole('button',{name:'Купить за Stars'}).click();await page.waitForTimeout(2500);const created=orders.filter(o=>o.body.includes('"license_id"'));expect(created.length).toBe(1);expect(created[0].status).toBe(201);expect(created[0].body).toMatch(/"license_id":"[A-Za-z0-9]{8}"/);expect(created[0].body).toContain('"amount_xtr":123');});

test('responsive layout keeps all pages and admin form inside narrow Telegram viewports',async({page})=>{for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});await page.goto('/admin/projects');await expect(page.getByRole('heading',{name:'Добавить проект'})).toBeVisible();const metrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth:window.innerWidth}));expect(metrics.scrollWidth).toBeLessThanOrEqual(metrics.innerWidth+1);const labelBox=await page.getByText('Название',{exact:true}).boundingBox();const inputBox=await page.getByLabel('Название').boundingBox();expect(labelBox).not.toBeNull();expect(inputBox).not.toBeNull();expect(inputBox!.width).toBeGreaterThan(240);expect(inputBox!.y).toBeGreaterThan(labelBox!.y);await page.goto('/settings');await expect(page.getByRole('heading',{name:'Настройки'})).toBeVisible();const settingsMetrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth:window.innerWidth}));expect(settingsMetrics.scrollWidth).toBeLessThanOrEqual(settingsMetrics.innerWidth+1)}});
