import {test,expect,type Page} from '@playwright/test';

async function installTelegramMock(page:Page){
  await page.route('https://telegram.org/js/telegram-web-app.js',route=>route.fulfill({contentType:'application/javascript',body:''}));
  await page.addInitScript(()=>{(window as any).Telegram={WebApp:{ready(){},expand(){},enableClosingConfirmation(){},initData:'development-test-init-data',initDataUnsafe:{user:{id:777,first_name:'Premium',username:'cloud_user'}},colorScheme:'dark',viewportStableHeight:844,BackButton:{show(){},hide(){},onClick(){},offClick(){}},MainButton:{setParams(){},showProgress(){},hideProgress(){},onClick(){},offClick(){},hide(){}},SecondaryButton:{setParams(){},onClick(){},offClick(){},hide(){}},HapticFeedback:{impactOccurred(){},selectionChanged(){},notificationOccurred(){}},CloudStorage:{getItem(_k:string,cb:(error:null,value:string)=>void){cb(null,'')},setItem(_k:string,_v:string,cb:(error:null,stored:boolean)=>void){cb(null,true)}},openInvoice(_url:string,cb:(status:string)=>void){cb('cancelled')}}};});
}

test.beforeEach(async({page})=>{await installTelegramMock(page)});

test('premium dashboard is responsive and has no unexpected runtime errors',async({page})=>{const errors:string[]=[];page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('401 (Unauthorized)'))errors.push(msg.text())});await page.goto('/');await expect(page.getByText('Инструменты, которые')).toBeVisible();await expect(page.getByRole('navigation',{name:'Основная навигация'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();expect(errors).toEqual([]);const unnamed=await page.locator('button').evaluateAll(buttons=>buttons.filter(button=>!(button.getAttribute('aria-label')||button.textContent?.trim())).length);expect(unnamed).toBe(0)});

test('primary navigation and local product pages render',async({page})=>{await page.goto('/');await page.getByRole('link',{name:/Поиск/}).click();await expect(page.getByRole('heading',{name:'Найдите готовое решение'})).toBeVisible();await page.getByRole('link',{name:/Premium/}).click();await expect(page.getByRole('heading',{name:/Больше скорости/})).toBeVisible();await page.getByRole('link',{name:/Профиль/}).click();await expect(page.getByText('Telegram подтверждён')).toBeVisible()});

test('development catalog exposes only non-template test products and opens checkout CTA',async({page})=>{await page.goto('/search');await expect(page.getByRole('heading',{name:'Найдите готовое решение'})).toBeVisible();expect(await page.locator('select[aria-label="Тип продукта"] option').allTextContents()).not.toContain('Шаблоны');await expect(page.getByText('Запись и бронирование')).toBeVisible({timeout:10_000});await page.getByRole('button',{name:'Открыть Запись и бронирование'}).click();await expect(page.getByRole('heading',{name:'Запись и бронирование'})).toBeVisible();await expect(page.getByRole('button',{name:'Купить за Stars'})).toBeVisible();});

test('profile is fully formed and settings controls are actionable',async({page})=>{await page.goto('/profile');await expect(page.getByRole('heading',{name:'Premium'})).toBeVisible();await expect(page.getByText('Ваш профиль')).toBeVisible();await expect(page.getByRole('button',{name:'Открыть настройки'})).toBeVisible();await expect(page.getByRole('button',{name:'История покупок'})).toBeVisible();await page.getByRole('button',{name:'Открыть настройки'}).click();await expect(page.getByRole('heading',{name:'Настройки'})).toBeVisible();await expect(page.getByRole('heading',{name:'Интерфейс',exact:true})).toBeVisible();await expect(page.getByText('Приватность и уведомления')).toBeVisible();await expect(page.getByRole('combobox',{name:'Тема интерфейса'})).toBeVisible();await expect(page.getByRole('switch',{name:'Приватный режим'})).toBeVisible();});

test('all secondary routes render without runtime failures',async({page})=>{const routes:[string,string][]=[['/settings','Настройки'],['/notifications','Уведомления'],['/referral','Делитесь инструментами'],['/statistics','Статистика'],['/history','История'],['/achievements','Достижения'],['/leaderboard','Личный рейтинг'],['/payments','Платежи'],['/subscription','Подписка и доступ'],['/support','Мы рядом'],['/faq','Частые вопросы'],['/about','Cloud Bot'],['/terms','Условия использования'],['/privacy','Конфиденциальность'],['/favorites','Избранное']];for(const[route,title]of routes){await test.step(route,async()=>{await page.goto(route);const heading=page.getByRole('heading',{name:title,exact:true}).first();if(route==='/history'&&!await heading.isVisible().catch(()=>false)){await expect(page.getByRole('alert')).toBeVisible()}else await expect(heading).toBeVisible({timeout:10_000})})}await page.close()});
