import {beforeEach,afterEach,afterAll,describe,expect,it,vi} from 'vitest';
import request from 'supertest';
import type {Express} from 'express';

describe('project admin security workflow',()=>{
  let app:Express;
  beforeEach(async()=>{vi.resetModules();process.env.NODE_ENV='test';process.env.ALLOW_DEV_LOGIN='true';process.env.DB_DRIVER='sqlite';process.env.STORAGE_DRIVER='local';process.env.DATABASE_PATH=`./data/project-admin-security-${Date.now()}-${Math.random().toString(36).slice(2)}.sqlite`;process.env.WEBHOOK_SECRET='test-secret-token-123';const {db,migrate}=await import('../server/db');await migrate();await db.exec('delete from audit_log; delete from product_assets; delete from products; delete from users; delete from admin_users;');app=(await import('../server/app')).createApp()});
  afterEach(async()=>{await (await import('../server/app')).closeRuntimeResources();await (await import('../server/db')).closeDb()});
  afterAll(async()=>{});
  async function token(id:number){return (await request(app).post('/api/auth/telegram').send({devTelegramId:id})).body.token as string}
  it('rejects anonymous and regular users on access and create',async()=>{await request(app).get('/api/me/access').expect(401);await request(app).post('/api/admin/products').send({title:'x',result:'x',type:'ready_bot',category:'x'}).expect(401);const t=await token(101);await request(app).get('/api/me/access').set('Authorization',`Bearer ${t}`).expect(200,{role:null,canCreateProjects:false,canPublishProjects:false});await request(app).post('/api/admin/products').set('Authorization',`Bearer ${t}`).send({title:'x',result:'x',type:'ready_bot',category:'x'}).expect(403)});
  it('forces draft creation and rejects invalid slug/status',async()=>{const {bootstrapAdmins,db}=await import('../server/db');await bootstrapAdmins('102');const t=await token(102);const created=await request(app).post('/api/admin/products').set('Authorization',`Bearer ${t}`).send({title:'x',result:'x',type:'ready_bot',category:'x',slug:'Bad Slug',status:'published'}).expect(400);expect(created.body.error.code).toBe('validation_failed');const ok=await request(app).post('/api/admin/products').set('Authorization',`Bearer ${t}`).send({title:'x',result:'x',type:'ready_bot',category:'x',slug:'valid-slug',status:'published'}).expect(201);expect(ok.body.status).toBe('draft');expect((await db.prepare('select status from products where id=?').get(ok.body.id) as any).status).toBe('draft')});
  it('allows editor upload only for draft and publish only once after approved scan',async()=>{const {bootstrapAdmins,db}=await import('../server/db');await bootstrapAdmins('103');const t=await token(103);const p=await request(app).post('/api/admin/products').set('Authorization',`Bearer ${t}`).send({title:'x',result:'x',type:'ready_bot',category:'x',slug:'draft-project',status:'draft'});const missing=await request(app).post('/api/admin/assets/upload').set('Authorization',`Bearer ${t}`).field('productId','missing').field('version','1.0.0').attach('file',Buffer.from('not zip'),'x.zip').expect(404);expect(missing.body.error.code).toBe('draft_product_not_found');await db.prepare("insert into product_assets(id,product_id,version,storage_key,file_name,mime_type,size_bytes,status) values(?,?,?,?,?,?,?,?)").run('asset-1',p.body.id,'1.0.0','products/x.zip','x.zip','application/zip',1,'approved');await request(app).post('/api/admin/assets/asset-1/publish').set('Authorization',`Bearer ${t}`).expect(200);await request(app).post('/api/admin/assets/asset-1/publish').set('Authorization',`Bearer ${t}`).expect(409);expect((await db.prepare('select status from products where id=?').get(p.body.id) as any).status).toBe('published')});
  it('rolls back the complete publish transition when the project update fails',async()=>{const {bootstrapAdmins,db}=await import('../server/db');await bootstrapAdmins('104');const t=await token(104);const p=await request(app).post('/api/admin/products').set('Authorization',`Bearer ${t}`).send({title:'x',result:'x',type:'ready_bot',category:'x',slug:'rollback-project'});await db.prepare("insert into product_assets(id,product_id,version,storage_key,file_name,mime_type,size_bytes,status) values(?,?,?,?,?,?,?,?)").run('asset-rollback',p.body.id,'1.0.0','products/rollback.zip','rollback.zip','application/zip',1,'approved');await db.exec("CREATE TRIGGER fail_project_publish BEFORE UPDATE OF status ON products WHEN NEW.status='published' BEGIN SELECT RAISE(ABORT, 'forced_project_update_failure'); END");await request(app).post('/api/admin/assets/asset-rollback/publish').set('Authorization',`Bearer ${t}`).expect(500);await db.exec('DROP TRIGGER fail_project_publish');expect((await db.prepare('select status from product_assets where id=?').get('asset-rollback') as any).status).toBe('approved');expect((await db.prepare('select status from products where id=?').get(p.body.id) as any).status).toBe('draft')});
  it('allows only one concurrent publish transition',async()=>{const {bootstrapAdmins,db}=await import('../server/db');await bootstrapAdmins('105');const t=await token(105);const p=await request(app).post('/api/admin/products').set('Authorization',`Bearer ${t}`).send({title:'x',result:'x',type:'ready_bot',category:'x',slug:'race-project'});await db.prepare("insert into product_assets(id,product_id,version,storage_key,file_name,mime_type,size_bytes,status) values(?,?,?,?,?,?,?,?)").run('asset-race',p.body.id,'1.0.0','products/race.zip','race.zip','application/zip',1,'approved');const results=await Promise.all([request(app).post('/api/admin/assets/asset-race/publish').set('Authorization',`Bearer ${t}`),request(app).post('/api/admin/assets/asset-race/publish').set('Authorization',`Bearer ${t}`)]);expect(results.map(r=>r.status).sort()).toEqual([200,409]);expect((await db.prepare('select status from product_assets where id=?').get('asset-race') as any).status).toBe('published');expect((await db.prepare('select status from products where id=?').get(p.body.id) as any).status).toBe('published')});
});



