import {Component,lazy,Suspense,useEffect,type ErrorInfo,type ReactNode} from 'react';import {Navigate,Route,Routes,useNavigate} from 'react-router-dom';import {PageLoader,ErrorState} from '../components/ui';import {AppShell} from '../layouts/AppShell';import {startParam} from '../services/telegram';
const Dashboard=lazy(()=>import('../pages/DashboardPage'));const Search=lazy(()=>import('../pages/SearchPage'));const Product=lazy(()=>import('../pages/ProductPage'));const Favorites=lazy(()=>import('../pages/FavoritesPage'));
const named=<T extends Record<string,unknown>,K extends keyof T>(loader:()=>Promise<T>,key:K)=>lazy(async()=>({default:(await loader())[key] as React.ComponentType}));
const account=()=>import('../pages/AccountPages'),insights=()=>import('../pages/InsightPages'),premium=()=>import('../pages/PremiumPages'),info=()=>import('../pages/InfoPages');
const Profile=named(account,'ProfilePage'),Settings=named(account,'SettingsPage'),Notifications=named(account,'NotificationsPage');
const History=named(insights,'HistoryPage'),Statistics=named(insights,'StatisticsPage'),Achievements=named(insights,'AchievementsPage'),Leaderboard=named(insights,'LeaderboardPage');
const PremiumPage=named(premium,'PremiumPage'),Payments=named(premium,'PaymentsPage'),Subscription=named(premium,'SubscriptionPage');
const Support=named(info,'SupportPage'),FAQ=named(info,'FAQPage'),About=named(info,'AboutPage'),Terms=named(info,'TermsPage'),Privacy=named(info,'PrivacyPage'),More=named(info,'MorePage');
const Referral=named(account,'ReferralPage'),ProjectAdmin=lazy(()=>import('../pages/ProjectAdminPage'));
function DeepLink(){const nav=useNavigate();useEffect(()=>{const param=startParam();if(/^product_[A-Za-z0-9_-]{1,56}$/.test(param))nav(`/product/${param.slice(8)}`,{replace:true});else if(/^category_[A-Za-z0-9_-]{1,55}$/.test(param))nav(`/search?category=${encodeURIComponent(param.slice(9))}`,{replace:true})},[nav]);return null}
export default function App(){return <ErrorBoundary><DeepLink/><Suspense fallback={<PageLoader/>}><Routes><Route element={<AppShell/>}><Route index element={<Dashboard/>}/><Route path="search" element={<Search/>}/><Route path="product/:slug" element={<Product/>}/><Route path="favorites" element={<Favorites/>}/><Route path="profile" element={<Profile/>}/><Route path="settings" element={<Settings/>}/><Route path="notifications" element={<Notifications/>}/><Route path="history" element={<History/>}/><Route path="statistics" element={<Statistics/>}/><Route path="achievements" element={<Achievements/>}/><Route path="leaderboard" element={<Leaderboard/>}/><Route path="premium" element={<PremiumPage/>}/><Route path="payments" element={<Payments/>}/><Route path="subscription" element={<Subscription/>}/><Route path="referral" element={<Referral/>}/><Route path="admin/projects" element={<ProjectAdmin/>}/><Route path="support" element={<Support/>}/><Route path="faq" element={<FAQ/>}/><Route path="about" element={<About/>}/><Route path="terms" element={<Terms/>}/><Route path="privacy" element={<Privacy/>}/><Route path="more" element={<More/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></Suspense></ErrorBoundary>}
class ErrorBoundary extends Component<{children:ReactNode},{error:Error|null}>{state:{error:Error|null}={error:null};static getDerivedStateFromError(error:Error){return{error}}componentDidCatch(error:Error,info:ErrorInfo){console.error('ui_boundary_failed',error,info.componentStack)}render(){return this.state.error?<main className="app-content"><ErrorState error={this.state.error} retry={()=>{this.setState({error:null});location.reload()}}/></main>:this.props.children}}
