import { api } from './client';
import type { AuthResponse, LicensePlan, Order, Product, ProductDetail, ProductFilters, Purchase, User } from '../types/api';
export const authTelegram=(initData:string)=>api<AuthResponse>('/auth/telegram',{method:'POST',body:JSON.stringify({initData,devTelegramId:import.meta.env.DEV?'777':undefined})});
export const getMe=()=>api<{user:User}>('/me');
export const getProducts=(filters:ProductFilters={},signal?:AbortSignal)=>api<{items:Product[];limit:number;offset:number}>(`/products?${new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)]))}`,{signal});
export const getProduct=(slug:string,signal?:AbortSignal)=>api<ProductDetail>(`/products/${encodeURIComponent(slug)}`,{signal});
export const getPurchases=()=>api<{items:Purchase[]}>('/me/purchases');
export const createOrder=(licenseId:string,idempotencyKey:string)=>api<{order:Order;idempotent:boolean}>('/orders',{method:'POST',headers:{'Idempotency-Key':idempotencyKey},body:JSON.stringify({licenseId,idempotencyKey})});
export const getOrder=(orderId:string)=>api<{order:Order&{created_at:string}}>(`/orders/${orderId}`);
export const createInvoice=(orderId:string)=>api<{invoiceLink:string}>(`/orders/${orderId}/invoice`,{method:'POST'});
export const createDownload=(purchaseId:string)=>api<{url:string;expiresIn:number}>(`/purchases/${purchaseId}/download`,{method:'POST'});
export const logout=()=>api<{ok:true}>('/auth/logout',{method:'POST'});
export type { LicensePlan };
