import type {HTMLAttributes,ReactNode } from 'react';import {motion,type HTMLMotionProps} from 'framer-motion';import {LoaderCircle,RefreshCw,Sparkles} from 'lucide-react';import {cn} from '../utils/cn';import {haptic} from '../services/telegram';
export function Button({className,children,onClick,...props}:HTMLMotionProps<'button'>){return <motion.button whileTap={{scale:.96}} whileHover={{y:-1}} className={cn('btn',className)} onClick={e=>{haptic.tap();onClick?.(e)}} {...props}>{children}</motion.button>}
export function Card({className,...props}:HTMLAttributes<HTMLDivElement>){return <div className={cn('glass-card',className)} {...props}/>}
export function Badge({children,className}:{children:ReactNode;className?:string}){return <span className={cn('badge-premium',className)}>{children}</span>}
export function Switch({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){return <button role="switch" aria-checked={checked} aria-label={label} className={cn('switch',checked&&'is-on')} onClick={()=>{haptic.select();onChange(!checked)}}><motion.span layout transition={{type:'spring',stiffness:600,damping:34}}/></button>}
export function Skeleton({className}:{className?:string}){return <div aria-hidden className={cn('skeleton',className)}/>}
export function PageLoader(){return <div className="state-card" role="status" aria-live="polite"><LoaderCircle className="animate-spin" aria-hidden/><b>Загружаем пространство</b><span>Синхронизируем данные с Telegram</span></div>}
export function EmptyState({title,text,action,actionLabel='Обновить'}:{title:string;text:string;action?:()=>void;actionLabel?:string}){return <Card className="state-card"><span className="state-icon"><Sparkles/></span><b>{title}</b><span>{text}</span>{action&&<Button onClick={action}><RefreshCw size={16}/>{actionLabel}</Button>}</Card>}
export function ErrorState({retry}:{error:Error;retry:()=>void}){return <Card className="state-card error" role="alert"><b>Что-то пошло не так</b><span>Не удалось загрузить данные. Попробуйте ещё раз.</span><Button onClick={retry}><RefreshCw size={16}/>Повторить</Button></Card>}
export function ProgressRing({value,size=72}:{value:number;size?:number}){const r=28,c=2*Math.PI*r;return <div className="progress-ring" style={{width:size,height:size}}><svg viewBox="0 0 64 64"><circle cx="32" cy="32" r={r}/><motion.circle cx="32" cy="32" r={r} initial={{strokeDashoffset:c}} animate={{strokeDashoffset:c*(1-value/100)}} style={{strokeDasharray:c}}/></svg><b>{value}%</b></div>}
