-- Reference-only snapshot of the current PostgreSQL schema.
-- Runtime startup and `npm run db:migrate` apply immutable files from
-- server/db/postgres-migrations/ and never execute this file.
-- Regenerate this snapshot from migrations when the schema changes.
